@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzbmVha2VyLXNlZWtlcnMiLCJzdWIiOiJyeWFuIiwiaWQiOjEsImF1dGhvcml0aWVzIjoiIiwiZXhwIjoxNjQ1NzM1MTI1fQ.GEqkwrXODK2fY4XAnGrPXlkwVp_0dri2RUmN-_nrdsc
@host = http://localhost:8080

### GET ALL USERS

GET {{host}}/user HTTP/1.1
Authorization: Bearer {{jwt}}

### GET ALL ROLES

GET {{host}}/user/role HTTP/1.1
Authorization: Bearer {{jwt}}

### GET USER BY USERNAME (RYAN)

GET {{host}}/user/ryan HTTP/1.1

### CREATE USER

POST {{host}}/user/create HTTP/1.1
Content-Type: application/json

{
    "username": "ryan",
    "password": "P@ssw0rd",
    "confirmPassword": "P@ssw0rd"
}

### AUTHENTICATE USER 

POST {{host}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "user",
    "password": "ehCX7MexUCb&T7"
}

### GET ALL BRANDS

GET {{host}}/sneakerseekers/brand HTTP/1.1

### ADD BRAND

POST {{host}}/sneakerseekers/brand HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "brandId": 1,
    "brandName": "Nike"
}

### GET ALL CONDITIONS

GET {{host}}/sneakerseekers/condition HTTP/1.1

### GET ALL EVENTS

GET {{host}}/sneakerseekers/event HTTP/1.1

### ADD EVENT

POST {{host}}/sneakerseekers/event HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "eventId": 1,
    "eventDate": "2022-12-25",
    "numTable": 100,
    "eventImage": "https://www.gicc.com/wp-content/uploads/2017/03/home-slider1.png",
    "locationId": 1
}

### GET FAVORITE BY APP USER ID 1

GET {{host}}/sneakerseekers/favorite/1 HTTP/1.1
Authorization: Bearer {{jwt}}

### ADD FAVORITE

POST {{host}}/sneakerseekers/favorite HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "favoriteId": 1,
    "styleId": 1,
    "appUserId": 1
}

### ADD FAVORITE NEW

POST {{host}}/sneakerseekers/favorite HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "styleId": 1,
    "styleName": "Nike Rare Shoes That Aren't In Database",
    "description": "These shoes do not exist in the database yet. They should be added to the styles table, and then to favorites.",
    //brand: need to link to existing brands
    "brand": {
        "brandId": 1,
        "brandName": "Nike",
    },
    "releaseDate": "2022-01-01",
    "image": "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/7dc49569-2d66-47bd-8139-91f671b3f1e4/court-legacy-mens-shoe-Lswv5z.png",
    "colorway": "Black/White/Tan"
}


### DELETE FAVORITE BY ID

DELETE {{host}}/sneakerseekers/favorite/1 HTTP/1.1
Authorization: Bearer {{jwt}}

### GET FOLLOWS BY FOLLOWER ID 1

GET {{host}}/sneakerseekers/follow/1
Authorization: Bearer {{jwt}}

### ADD FOLLOW

POST {{host}}/sneakerseekers/follow HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "followerId": 1,
    "vendorId": 1
}

### DELETE FOLLOW BY FOLLOWER ID AND VENDOR ID

DELETE {{host}}/sneakerseekers/follow/1/1 HTTP/1.1
Authorization: Bearer {{jwt}}

### GET LISTINGS BY TABLE ID

GET {{host}}/sneakerseekers/listing/1

### ADD LISTING

POST {{host}}/sneakerseekers/listing HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "listingId": 1,
    "styleId": 1,
    "listingPrice": 200,
    "quantity": 1,
    "tableId": 1
}

### DELETE LISTING BY ID

DELETE {{host}}/sneakerseekers/listing/1 HTTP/1.1
Authorization: Bearer {{jwt}}

### GET ALL LOCATIONS

GET {{host}}/sneakerseekers/location

### GET LOCATION BY ID

GET {{host}}/sneakerseekers/location/1

### ADD LOCATION

POST {{host}}/sneakerseekers/location HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "locationId": 1,
    "locationName": "Georgia International Convention Center",
    "locationAddress": "2000 Convention Center Concourse, College Park, GA 30337",
    "locationCity": "Atlanta"
}

### GET STYLE BY ID

GET {{host}}/sneakerseekers/style/1

### ADD STYLE

POST {{host}}/sneakerseekers/style HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "styleId": 1,
    "styleName": "Air Jordan 1 Retro High OG Patent Bred",
    "brandId": 1,
    "description": "Featuring a classic mix of hues, the Air Jordan 1 Retro High OG 'Patent Bred' also sports an elevated construction. Built entirely with patent leather, the shoe's upper appears in a familiar mix of black and Varsity Red, with perforations on the toe box offering breathability. Underfoot, a white Air midsole provides cushioning and contrast, giving way to a Varsity Red finish on the concentric rubber outsole, which is included for traction.",
    "releaseYear": 2021,
    "styleImage": "https://cdn.flightclub.com/1250/TEMPLATE/272669/1.jpg"

}


### GET TABLES BY EVENT ID

GET {{host}}/sneakerseekers/table/1

### ADD TABLE

POST {{host}}/sneakerseekers/table HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "tableId": 1,
    "eventId": 1,
    "appUserId": 1,
    "isBooked": true,
    "tableNumber": 1
}

### UPDATE TABLE

PUT {{host}}/sneakerseekers/table/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "tableId": 1,
    "eventId": 1,
    "appUserId": 1,
    "isBooked": true,
    "tableNumber": 2
}

### GET ALL UPGRADE REQUESTS

GET {{host}}/sneakerseekers/upgraderequest
Authorization: Bearer {{jwt}}

### ADD UPGRADE REQUEST

POST {{host}}/sneakerseekers/upgraderequest HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "upgradeRequestId": 1,
    "appUserId": 2
}

### DELETE UPGRADE REQUEST BY ID

DELETE {{host}}/sneakerseekers/upgraderequest/1 HTTP/1.1
Authorization: Bearer {{jwt}}
